Pages/Create.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SkinZoneAppWeb.Models;
using SkinZoneAppWeb.Services;
using System.Text.RegularExpressions;

namespace SkinZoneAppWeb.Pages
{
    [Authorize]
    public class CreateModel : PageModel
    {
        public SelectList TipoOptionItems { get; set; }

        private ISkinService _service;

        public CreateModel(ISkinService service) 
        {
            _service = service;
        }

        public void OnGet()
        {
            TipoOptionItems = new SelectList(_service.ObterTodosTipos(),
                                                    nameof(Tipo.TipoId),
                                                nameof(Tipo.Descricao));
        }

        [BindProperty]
        public Skin Skin { get; set; }

        public IActionResult OnPost() 
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (!Skin.DisponivelParaRetirada)
            {
                Skin.DataRetirada = Skin.DataCadastro.AddDays(Skin.TradeLock);
            }
            if (Skin.TradeLock < 1)
            {
                Skin.TradeLock = 0;
            }

            _service.Incluir(Skin);

            return RedirectToPage("/Index");
        }
    }
}

Pages/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SkinZoneAppWeb.Models;
using SkinZoneAppWeb.Services;

namespace SkinZoneAppWeb.Pages
{
    public class DetailsModel : PageModel
    {
        private ISkinService _service;
        public string DescricaoMarca {  get; set; }

        public DetailsModel(ISkinService service) 
        {
            _service = service;
        }

        public Skin Skin { get; private set; }
        public IActionResult OnGet(int id)
        {
            Skin = _service.Obter(id);
            if (Skin.TipoId is not null)
            {
                DescricaoMarca = _service.ObterTipo(Skin.TipoId.Value).Descricao;
            }
            
            if (Skin == null)
            {
                return NotFound();
            }

            return Page();
        }
    }
}

Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SkinZoneAppWeb.Models;
using SkinZoneAppWeb.Services;

namespace SkinZoneAppWeb.Pages
{
    public class EditModel : PageModel
    {
        public SelectList TipoOptionItems { get; set; }

        private ISkinService _service;

        public EditModel(ISkinService service)
        {
            _service = service;
        }

        [BindProperty]
        public Skin Skin { get; set; }

        public IActionResult OnGet(int id)
        {
            Skin = _service.Obter(id);

            TipoOptionItems = new SelectList(_service.ObterTodosTipos(),
                                        nameof(Tipo.TipoId),
                                        nameof(Tipo.Descricao));

            if (Skin == null)
            {
                return NotFound();
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (!Skin.DisponivelParaRetirada)
            {
                Skin.DataRetirada = Skin.DataCadastro.AddDays(Skin.TradeLock);
            }
            if (Skin.TradeLock < 1)
            {
                Skin.TradeLock = 0;
            }

            _service.Alterar(Skin);

            TempData["TempMensagemSucesso"] = true;

            return RedirectToPage("/Index");
        }

        public IActionResult OnPostExclusao()
        {
            _service.Excluir(Skin.SkinId);

            return RedirectToPage("/Index");
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SkinZoneAppWeb.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using SkinZoneAppWeb.Models;
using SkinZoneAppWeb.Services;

namespace SkinZoneAppWeb.Pages;

public class IndexModel : PageModel
{


    private ISkinService _service;

    public IndexModel(ISkinService service)
    {
        _service = service;
    }

    public IList<Skin> ListaSkins { get; private set; }

    public void OnGet()
    {
        ViewData["Title"] = "Home page";

        ListaSkins = _service.ObterTodos();
    }

    public void OnPost() 
    {

    }
}

Pages/Privacy - Cópia.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SkinZoneAppWeb.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Tipos/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SkinZoneAppWeb.Data;
using SkinZoneAppWeb.Models;

namespace SkinZoneAppWeb.Pages.Tipos
{
    public class CreateModel : PageModel
    {
        private readonly SkinZoneDbContext _context;

        public CreateModel(SkinZoneDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Tipo Tipo { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Tipo == null || Tipo == null)
            {
                return Page();
            }

            _context.Tipo.Add(Tipo);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Tipos/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SkinZoneAppWeb.Data;
using SkinZoneAppWeb.Models;

namespace SkinZoneAppWeb.Pages.Tipos
{
    public class DetailsModel : PageModel
    {
        private readonly SkinZoneDbContext _context;

        public DetailsModel(SkinZoneDbContext context)
        {
            _context = context;
        }

      public Tipo Tipo { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Tipo == null)
            {
                return NotFound();
            }

            var tipo = await _context.Tipo.FirstOrDefaultAsync(m => m.TipoId == id);
            if (tipo == null)
            {
                return NotFound();
            }
            else 
            {
                Tipo = tipo;
            }
            return Page();
        }
    }
}

Pages/Tipos/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SkinZoneAppWeb.Data;
using SkinZoneAppWeb.Models;

namespace SkinZoneAppWeb.Pages.Tipos
{
    public class EditModel : PageModel
    {
        private readonly SkinZoneDbContext _context;

        public EditModel(SkinZoneDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Tipo Tipo { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Tipo == null)
            {
                return NotFound();
            }

            var tipo =  await _context.Tipo.FirstOrDefaultAsync(m => m.TipoId == id);
            if (tipo == null)
            {
                return NotFound();
            }
            Tipo = tipo;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Tipo).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TipoExists(Tipo.TipoId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool TipoExists(int id)
        {
          return (_context.Tipo?.Any(e => e.TipoId == id)).GetValueOrDefault();
        }
    }
}

Pages/Create.cshtml
@page "/create"
@{
    ViewData["Title"] = "Inserção de novos itens";
}

@using static SkinZoneAppWeb.Models.Skin
@model SkinZoneAppWeb.Pages.CreateModel

<div class="row pt-5">
    <div class="col-md-4">
        <form method="post">
            <h4>Adicionar Skin</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Skin.Nome" class="control-label"></label>
                <input asp-for="Skin.Nome" class="form-control" />
                <span asp-validation-for="Skin.Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Skin.ImagemUri" class="control-label"></label>
                <input asp-for="Skin.ImagemUri" class="form-control" />
                <span asp-validation-for="Skin.ImagemUri" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Skin.Preco" class="control-label"></label>
                <input asp-for="Skin.Preco" class="form-control" />
                <span asp-validation-for="Skin.Preco" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Skin.Desgaste" class="control-label"></label>
                <select asp-for="Skin.Desgaste" asp-items="Html.GetEnumSelectList<NivelDesgaste>()" class="form-control">
                    <option value="">Selecione o nível de desgaste...</option>
                </select>
                <span asp-validation-for="Skin.Desgaste" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Skin.DataCadastro" class="control-label"></label>
                <input asp-for="Skin.DataCadastro" class="form-control" />
                <span asp-validation-for="Skin.DataCadastro" class="text-danger"></span>
            </div>

            <div class="form-group mt-3 mb-3">
                <input class="form-check-input" asp-for="Skin.DisponivelParaRetirada" />
                <label asp-for="Skin.DisponivelParaRetirada"></label>
            </div>

            <div class="form-group" id="tradeLockField">
                <label asp-for="Skin.TradeLock" class="control-label"></label>
                <input asp-for="Skin.TradeLock" class="form-control" value="0" />
                <span asp-validation-for="Skin.TradeLock" class="text-danger"></span>
            </div>

            <div class="form-group mt-3 mb-3">
                <label asp-for="Skin.TipoId" class="control-label"></label>
                <select class="form-select" asp-for="Skin.TipoId"
                        asp-items="Model.TipoOptionItems">
                    <option value="">Selecione uma opção</option>
                </select>
                <span asp-validation-for="Skin.TipoId" class="text-danger">
                </span>
            </div>


            <div class="form-group mt-4">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts{

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var disponivelParaRetiradaCheckbox = document.getElementById("Skin_DisponivelParaRetirada");
            var tradeLockField = document.getElementById("tradeLockField");

            function updateTradeLockVisibility() {
                tradeLockField.style.display = disponivelParaRetiradaCheckbox.checked ? "none" : "block";
            }

            disponivelParaRetiradaCheckbox.addEventListener("change", updateTradeLockVisibility);

            updateTradeLockVisibility();
        });
    </script>


}

Pages/Details.cshtml
@page "/skin/{slug}/{id:int:min(1)}"
@model SkinZoneAppWeb.Pages.DetailsModel

@{
    var Skin = Model.Skin;
}

<h2 class="my-3">@Skin.Nome</h2>
<div class="row">
    <div class="col-4">
        <img class="img-fluid rounded" src="@Skin.ImagemUri">
    </div>
    <div class="col-6">
        <h4 class="my-3">Sobre:</h4>
        <ul>
            <li><label asp-for="Skin.Desgaste"></label>: 
                @Skin.Desgaste
            </li>
            <li><label asp-for="Skin.Preco"></label>: 
                @Html.DisplayFor(model => Skin.Preco)
            </li>
            <li>
                <label asp-for="Skin.DataRetirada"></label>:
                @if (Skin.DisponivelParaRetirada)
                {
                    <span class="text-success">Disponível para retirada imediata</span>
                }
                else
                {
                    <span class="text-warning"> @Html.DisplayFor(model => Skin.DataRetirada)</span>
                }
            </li>
            @if(Model.DescricaoMarca is not null)
            {
                <li>

                    <label asp-for="Skin.TipoId"></label>:
                    @Html.DisplayFor(model => model.DescricaoMarca)
                </li>
            }

        </ul>

        @if (User.Identity.IsAuthenticated)
        {
            <a class="btn btn-primary"
               asp-page="/Edit"
               asp-route-slug="@Skin.NomeSlug"
               asp-route-id="@Skin.SkinId">Editar</a>
        }
    </div>
</div>

Pages/Edit.cshtml
@page "/@slug"
@{
    ViewData["Title"] = "Edição de Item";
}

@using static SkinZoneAppWeb.Models.Skin
@model SkinZoneAppWeb.Pages.EditModel


<div class="row pt-5">
    <div class="col-md-4">
        <form method="post">
            <h4>Editar Skin</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Skin.SkinId" />

            <div class="form-group">
                <label asp-for="Skin.Nome" class="control-label"></label>
                <input asp-for="Skin.Nome" class="form-control" />
                <span asp-validation-for="Skin.Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Skin.ImagemUri" class="control-label"></label>
                <input asp-for="Skin.ImagemUri" class="form-control" />
                <span asp-validation-for="Skin.ImagemUri" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Skin.Preco" class="control-label"></label>
                <input asp-for="Skin.Preco" class="form-control" />
                <span asp-validation-for="Skin.Preco" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Skin.Desgaste" class="control-label"></label>
                <select asp-for="Skin.Desgaste" asp-items="Html.GetEnumSelectList<NivelDesgaste>()" class="form-control">
                    <option value="">Selecione o nível de desgaste...</option>
                </select>
                <span asp-validation-for="Skin.Desgaste" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Skin.DataCadastro" class="control-label"></label>
                <input asp-for="Skin.DataCadastro" class="form-control" />
                <span asp-validation-for="Skin.DataCadastro" class="text-danger"></span>
            </div>

            <div class="form-group mt-3 mb-3">
                <input class="form-check-input" asp-for="Skin.DisponivelParaRetirada" />
                <label asp-for="Skin.DisponivelParaRetirada"></label>
            </div>

            <div class="form-group" id="tradeLockField">
                <label asp-for="Skin.TradeLock" class="control-label"></label>
                <input asp-for="Skin.TradeLock" class="form-control" value="0" />
                <span asp-validation-for="Skin.TradeLock" class="text-danger"></span>
            </div>

            <div class="form-group mt-3 mb-3">
                <label asp-for="Skin.TipoId" class="control-label"></label>
                <select class="form-select" asp-for="Skin.TipoId"
                        asp-items="Model.TipoOptionItems">
                    <option value="">Selecione uma opção</option>
                </select>
                <span asp-validation-for="Skin.TipoId" class="text-danger">
                </span>
            </div>

            <div class="form-group mt-4">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <input type="submit" value="Excluir" class="btn btn-danger" asp-page-handler="Exclusao"/>
            </div>
        </form>
    </div>
</div>


@section Scripts{

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var disponivelParaRetiradaCheckbox = document.getElementById("Skin_DisponivelParaRetirada");
            var tradeLockField = document.getElementById("tradeLockField");

            function updateTradeLockVisibility() {
                tradeLockField.style.display = disponivelParaRetiradaCheckbox.checked ? "none" : "block";
            }

            disponivelParaRetiradaCheckbox.addEventListener("change", updateTradeLockVisibility);

            updateTradeLockVisibility();
        });
    </script>


}

Pages/Index.cshtml
@page
@model IndexModel



<div class="row justify-content-md-center">

    <h2 class ="text-center">Skins Disponíveis</h2>
    @if (TempData["TempMensagemSucesso"] != null)
    {
        <div class="alert alert-success mt-5"
             role="alert" style="width: 80%">
            <h4 class="alert-heading">Sucesso!</h4>
            Operação realizada com sucesso!
        </div>
    }


    @foreach (var item in Model.ListaSkins)
    {
        <div class="card col-3 m-2">
            <img src="@item.ImagemUri" class="p-3" style="border-radius: 25px">
            <div class="card-body">
                <h5 class="card-title">@item.Nome</h5>
                <p class="card-text">@item.Desgaste</p>
                <p class="card-text">
                    @if (item.DisponivelParaRetirada)
                    {
                        <span class="text-success">Disponível para retirada imediata</span>
                    }
                    else
                    {
                        <span class="text-warning">Retirada disponível em alguns dias</span>
                    }
                </p>
                <a class="btn btn-primary"
                asp-page="/Details"
                asp-route-slug="@item.NomeSlug"
                asp-route-id="@item.SkinId">Ver mais</a>
            </div>
        </div>
    }

</div>

Pages/Privacidade.cshtml
@page
@{
    ViewData["Title"] = "Política de Privacidade da SkinZone";
}

<style>
    body {
        font-family: 'Arial', sans-serif;
        line-height: 1.6;
        margin: 0;
        padding: 0;
    }

    h2 {
        border-bottom: 2px solid #343a40;
        padding-bottom: 10px;
        margin-top: 30px;
    }

    p {
        margin-bottom: 25px;
    }
</style>

<h1>@ViewData["Title"]</h1>

<p>A SkinZone valoriza a privacidade dos nossos clientes e se compromete a proteger as informações pessoais coletadas durante sua interação com nosso site. Esta Política de Privacidade descreve como coletamos, usamos e protegemos seus dados. Ao utilizar nossos serviços, você concorda com as práticas aqui descritas.</p>

<h2>Coleta de Informações Pessoais</h2>
<p>Coletamos informações pessoais, como nome, endereço de e-mail e informações de contato, quando você se registra em nossa plataforma ou realiza uma compra de skins de CS2.</p>

<h2>Uso de Informações Pessoais</h2>
<p>As informações pessoais coletadas são usadas para processar pedidos, fornecer suporte ao cliente e melhorar nossos serviços. Garantimos que suas informações serão utilizadas apenas para os fins previamente consentidos por você.</p>

<h2>Compartilhamento de Informações</h2>
<p>Não compartilhamos suas informações pessoais com terceiros, a menos que seja estritamente necessário para processar transações ou cumprir obrigações legais.</p>

<h2>Proteção de Dados</h2>
<p>Implementamos medidas de segurança para proteger suas informações contra acesso não autorizado e uso indevido.</p>

<h2>Seus Direitos</h2>
<p>Você tem o direito de acessar, corrigir ou excluir suas informações pessoais. Entre em contato conosco para exercer esses direitos ou se tiver alguma dúvida sobre nossa política de privacidade.</p>

<h2>Alterações na Política de Privacidade</h2>
<p>
    Esta Política de Privacidade pode ser atualizada periodicamente. Quaisquer alterações serão refletidas nesta página.<br />
    A privacidade e a segurança dos seus dados são importantes para a SkinZone. Agradecemos por escolher nossa empresa e estamos comprometidos em manter suas informações protegidas.</p>

Pages/Privacy - Cópia.cshtml
@page

@{
    ViewData["Title"] = "Privacy Policy";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

Pages/QuemSomos.cshtml
@page
@{
    ViewData["Title"] = "SkinZone";
}

<style>
    body {
        font-family: 'Arial', sans-serif;
        line-height: 1.6;
        margin: 0;
        padding: 0;
    }

    h2 {
        border-bottom: 2px solid #343a40;
        padding-bottom: 10px;
        margin-top: 30px;
    }

    p {
        margin-bottom: 25px;
    }

    li{
        margin-bottom: 20px;
    }

    h6{
        margin-bottom: 20px;
    }

    /* Adicionado o estilo para alinhar à direita */
    img {
        float: left;
        margin: 20px; /* Ajuste conforme necessário para espaçamento desejado */
        margin-right: 50px;
        max-width: 400px; /* Ajuste o valor conforme necessário para limitar a largura da imagem */
        height: auto; /* Garante que a altura seja ajustada proporcionalmente à largura */
    }

    /* Limpar o float para evitar problemas de layout */
    .clear {
        clear: both;
    }
</style>

<h1>@ViewData["Title"]</h1>

<p></p>


<h2>O Seu Destino Para Skins Exclusivas de CS2!</h2>

<p>
    Na SkinZone, somos apaixonados por tornar sua experiência no Counter Strike 2 (CS2) ainda mais emocionante e personalizada.<br />
    Nosso compromisso é fornecer a você as skins mais incríveis e desejadas para aprimorar o seu jogo.
</p>

<img src="/images/SkinZoneLogo.jpeg" alt="SkinZone Logo">

<h4>Por que escolher a SkinZone?</h4>
<ul>
    <li>Variedade Inigualável: Nossa coleção de skins é uma verdadeira zona de diversidade. Desde skins clássicas até criações exclusivas, temos algo para atender a todos os gostos.</li>
    <li>Qualidade Garantida: Todas as nossas skins são autênticas e de alta qualidade. Cada skin foi cuidadosamente selecionada para garantir que você receba o melhor.</li>
    <li>Atendimento ao Cliente de Primeira Classe: Nossa equipe dedicada está à disposição para ajudá-lo a encontrar as skins perfeitas e responder a todas as suas dúvidas. Sua satisfação é a nossa prioridade.</li>
    <li>Preços Competitivos: Na SkinZone, acreditamos que skins incríveis não precisam custar uma fortuna. Oferecemos preços competitivos para que você possa personalizar seu jogo sem esvaziar sua carteira.</li>
</ul>


<h6>Explore nossa ampla seleção de skins de CS2 e descubra como a SkinZone pode elevar sua experiência de jogo a um novo patamar. Junte-se a nós e faça parte da comunidade de jogadores que sabe onde encontrar as skins mais incríveis!</h6>
<h6>Estamos ansiosos para ajudá-lo a encontrar as skins perfeitas. Vá em frente e mergulhe na SkinZone hoje mesmo!</h6>